### ISSUE TITLE
Unable to download driver from Microsoft Update Catalog

### ISSUE THREAD

**Issue by ankushsvc** [OSDeploy/OSD#127] opened 2024-03-22 09:05 UTC
**Describe the bug**
OSDCloud unable to download firmware updates and drivers from MS Update catalog. 

**To Reproduce**
Image a device using OSDCloud with -firmware switch

**Expected behavior**
It should download driver successfully

**Screenshots**
<img width="581" alt="image" src="https://github.com/OSDeploy/OSD/assets/63633523/4f89808d-3cf7-4df4-ba69-ee42d525546a">

**Comment by ankushsvc** [comment] 2024-03-22 09:06
[2024-03-22-011807-Deploy-OSDCloud.log](https://github.com/OSDeploy/OSD/files/14720158/2024-03-22-011807-Deploy-OSDCloud.log)

**Comment by AkosBakos** [comment] 2024-03-22 10:31
I think your issue ist either coz of this:
![1](https://github.com/OSDeploy/OSD/assets/44706641/0ba08526-7848-4e3c-aaa5-1fbd61c05b16)

My workaround for this, are the following lines:
**_Register-PSRepository -Default -Verbose
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -Verbose
Install-Module -Name MSCatalog -Force -Verbose -SkipPublisherCheck -AllowClobber -Repository PSGallery_**

Or if you use in the beginning iex (irm functions.osdcloud.com)
Then you can use these one:
**_osdcloud-TrustPSGallery -Verbose
osdcloud-InstallPowerShellModule -Name 'MSCatalog'_**

**Comment by ankushsvc** [comment] 2024-03-22 12:05
@AkosBakos I have tried your suggestion and OSDCloud is able to download firmware updates but still failing to download drivers from MS Catalog. 
[2024-03-22-043812-Deploy-OSDCloud.log](https://github.com/OSDeploy/OSD/files/14722254/2024-03-22-043812-Deploy-OSDCloud.log)

**Comment by gwblok** [comment] 2024-03-22 13:15
@ankushsvc 
On your test computer, can you run

```PowerShell
Save-MsUpCatDriver -DestinationDirectory c:\drivers\test
```

Is that working?
I'm unable to reproduce the issue, so at this time, there isn't much I can do.

![image](https://github.com/OSDeploy/OSD/assets/26312309/7fdbf8f1-9bda-4573-9cd1-a3c1e58efdb9)
![image](https://github.com/OSDeploy/OSD/assets/26312309/98d78976-1d9c-4554-b3cf-78830486abcb)

**Comment by gwblok** [comment] 2024-03-22 13:22
Couple of extra thoughts for ya @ankushsvc ,
If you're looking for a guaranteed way to apply drivers during WinPE stage,  extract the driverpack into one of the 2 folders it checks on the USB drive.
![image](https://github.com/OSDeploy/OSD/assets/26312309/ef195609-9afd-42b6-a03d-db7f4fb29090)

OSDCloud will then DISM that driver pack into the machine during WinPE.

If you want it to update the BIOS from WU during the process, you can also check the box to have it download Windows Update drivers during Setup Complete phase.  It will reach out to WU and update any drivers (including BIOS) it finds.

**Comment by AkosBakos** [comment] 2024-03-22 13:23
Maybe it's a Dell specific issue, even some settings doesn't correct in the BIOS? On my test Surface and Lenovo devices, the peocess is working.

**Comment by ankushsvc** [comment] 2024-03-22 15:26
@gwblok Save-MsUpCatDriver does work in full windows but fails with terminating error in Windows PE. 
I won't able to  download Windows Update drivers during Setup Complete phase as device won't be able to connect to network after restart.
Issue is resolved now with help of my colleague. He made below changes in Invoke-CatalogRequest function and it works now in WinPE. 
Added a null check for ct100_catalogBody_updateMatches before invoking the MsUpCatResponse class.
`if ($null -eq $NoResults) {
            $ErrorText = $HtmlDoc.GetElementbyId("errorPageDisplayedError")
            if ($ErrorText) {
                throw "The catalog.update.microsoft.com site has encountered an error. Please try again later."
            } else {
                if($HtmlDoc.GetElementbyId("ctl00_catalogBody_updateMatches") -eq $null){
                    return $null
                } else {
                    [MsUpCatResponse]::new($HtmlDoc)
                }
            }
        } else {
            throw "$($NoResults.InnerText)$($Uri.Split("q=")[-1])"
        }`
Thanks @gwblok @AkosBakos

**Comment by gwblok** [comment] 2024-03-22 15:56
I've made the change in GitHub
https://github.com/OSDeploy/OSD/blob/master/Private/MSCatalog/Invoke-CatalogRequest.ps1

Added change to Release Notes 23.3.22

Changes go into effect the next module push.

**Comment by gwblok** [comment] 2024-03-29 20:00
I believe this is all working as expected now.  Closing Issue

**Closed by gwblok** 2024-03-29 20:00 UTC
